blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView,BlogCreateView, BlogUpdateView , BlogDetailView , BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blogs_list',cache_page(60)(BlogListView.as_view()),name='blogs_list'),
    path('create_blog',BlogCreateView.as_view(),name='create_blog'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('services.urls',namespace='services')),
    path('users/',include('users.urls',namespace='users')),
    path('blog/',include('blog.urls',namespace='blog')),
]

blog/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}

class Blog(models.Model):
    title = models.CharField(max_length=15,verbose_name='заголовок')
    description = models.TextField(verbose_name='содержимое статьи',**NULLABLE)
    image = models.ImageField(upload_to='blog/',verbose_name='изображение',**NULLABLE)
    views_count = models.IntegerField(default=0,verbose_name='количество просмотров')
    published_date = models.DateTimeField(verbose_name='дата публикации',auto_now_add=True)

    def __str__(self):
        return f'Название блога: {self.title}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.urls import reverse
from blog.models import Blog
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView , ListView , DetailView , DeleteView


class BlogCreateView(LoginRequiredMixin,CreateView):
    model = Blog
    fields = ('title','description','image',)
    success_url = reverse_lazy('blog:blogs_list')
    login_url = "users:login"


class BlogUpdateView(LoginRequiredMixin,UpdateView):
    model = Blog
    fields = ('title','description','image',)
    login_url = "users:login"

    def get_success_url(self):
        return reverse('blog:view',args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.is_staff:
            raise Http404
        return self.object
class BlogListView(ListView):
    model = Blog

    def get_queryset(self,*args,**kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        return queryset

class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blogs_list')
    login_url = "users:login"

    def test_func(self):
        return self.request.user.is_staff

blog/templates/blog/blog_confirm_delete.html
{% extends 'services/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <p>Действительно хотите удалить блог {{object.title}}?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a href="{% url 'blog:blogs_list' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'services/base.html' %}
{% load static %}

<title>Обзор блога</title>


{% block content %}
  <div class="row">
    <div class="col-md-4">
      <div class="card mb-4 box-shadow">
        <img class="card-img-top"
             src="{{ object.image }}"
             alt="Card image cap">
        <div class="card-body">
          <p class="card-text"><strong>{{ object.title }}</strong></p>
            <strong>{{ object.description }}</strong>
          <hr>
          Количество просмотров: <em>{{ object.views_count }}</em>
        </div>
        <div class="btn-group">
        {% if perms.blog.change_blog %}
          <a href="{% url 'blog:edit' object.pk  %}" type="button" class="btn btn-sm btn-outline-secondary">Редактировать</a>
        {% endif %}
        </div>
         <div class="btn-group">
         {% if perms.blog.delete_blog or user.is_superuser %}
          <a href="{% url 'blog:delete' object.pk  %}" type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>
         {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'services/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-success">
                             {% if object %}
                                Сохранить
                             {% else %}
                                Создать
                             {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'services/base.html' %}
{% load static %}

<title>Blogs</title>


{% block content %}
<div class="col-12 mb-5">
  <a href="{% url 'blog:create_blog' %}" class="btn btn-outline-primary">Создать блог</a>
</div>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                  <p class="card-text"><strong>{{ object.title }}</strong></p>
                  <p class="card-text">{{ object.description | truncatechars:20 }}</p>
                    <p class="card-text">Дата публикации: {{object.published_date}}</p>
                  <img class="card-img-top" height="300" src="{{ object.image }}">
                    <br>
                  <br><div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <a href="{% url 'blog:view' object.pk  %}" type="button" class="btn btn-sm btn-outline-secondary">К блогу</a>
                    </div>
                    <div class="btn-group">
                    {% if perms.blog.change_blog %}
                      <a href="{% url 'blog:edit' object.pk  %}" type="button" class="btn btn-sm btn-outline-secondary">Редактировать</a>
                    {% endif %}
                    </div>
                     <div class="btn-group">
                    {% if perms.blog.delete_blog or user.is_superuser %}
                      <a href="{% url 'blog:delete' object.pk  %}" type="button" class="btn btn-sm btn-outline-secondary">Удалить</a>
                    {% endif %}
                    </div>
                  </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
  </div>
</div>
{% endblock %}