blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView,BlogCreateView, BlogUpdateView , BlogDetailView , BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blogs_list',cache_page(60)(BlogListView.as_view()),name='blogs_list'),
    path('create_blog',BlogCreateView.as_view(),name='create_blog'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('services.urls',namespace='services')),
    path('users/',include('users.urls',namespace='users')),
    path('blog/',include('blog.urls',namespace='blog')),
]

services/urls.py
from django.urls import path
from services.apps import ServicesConfig
from services.views import Homepage,ContactTemplateView
from services.views import ClientCreateView,ClientListView,ClientDetailView,ClientUpdateView,ClientDeleteView
from services.views import MessageCreateView,MessageListView,MessageDetailView,MessageUpdateView,MessageDeleteView
from services.views import NewsletterCreateView,NewsletterUpdateView,NewsletterListView,NewsletterDetailView,NewsletterDeleteView
from services.views import LogsListView
from django.views.decorators.cache import cache_page

app_name = ServicesConfig.name


urlpatterns = [
    path('',cache_page(60)(Homepage.as_view()),name='home'),
    path('contacts/',ContactTemplateView.as_view(),name='contacts'),

    path('client_list/',ClientListView.as_view(),name='client_list'),
    path('create_client/',ClientCreateView.as_view(),name='create_client'),
    path('view_client/<int:pk>',ClientDetailView.as_view(),name='view_client'),
    path('edit_client/<int:pk>',ClientUpdateView.as_view(),name='edit_client'),
    path('delete_client/<int:pk>',ClientDeleteView.as_view(),name='delete_client'),

    path('message/create',MessageCreateView.as_view(),name='create_message'),
    path('message/list',MessageListView.as_view(),name='list_message'),
    path('message/view/<int:pk>',MessageDetailView.as_view(),name='view_message'),
    path('message/edit/<int:pk>',MessageUpdateView.as_view(),name='edit_message'),
    path('message/delete/<int:pk>',MessageDeleteView.as_view(),name='delete_message'),

    path('newsletter/create',NewsletterCreateView.as_view(),name='create_newsletter'),
    path('newsletter/edit/<int:pk>',NewsletterUpdateView.as_view(),name='edit_newsletter'),
    path('newsletter/list',NewsletterListView.as_view(),name='list_newsletter'),
    path('newsletter/view/<int:pk>',NewsletterDetailView.as_view(),name='view_newsletter'),
    path('newsletter/delete/<int:pk>',NewsletterDeleteView.as_view(),name='delete_newsletter'),

    path('logs/',LogsListView.as_view(),name='logs_list'),
]

users/urls.py
from django.contrib.auth.views import LoginView , LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import RegisterView , UserUpdateView , generate_new_password , UserListView , UserDetailView , UserDeleteView , email_verification

app_name = UsersConfig.name

urlpatterns = [
    path('login/',LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('register/',RegisterView.as_view(),name='register'),
    path('edit_user/<int:pk>/',UserUpdateView.as_view(),name='edit_user'),
    path('generate_password/',  generate_new_password, name='generate_new_password'),
    path('user_list/',  UserListView.as_view(), name='user_list'),
    path('view_user/<int:pk>/',  UserDetailView.as_view(), name='view_user'),
    path('delete_user/<int:pk>/',  UserDeleteView.as_view(), name='delete_user'),
    path('confirm/<str:token>/',  email_verification, name='confirm'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    phone = models.CharField(max_length=20,verbose_name='номер телефона',null=True,blank=True)
    avatar = models.ImageField(upload_to='users/',verbose_name='аватар',null=True,blank=True)
    token = models.CharField(verbose_name='Token',max_length=100,null=True,blank=True)

    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    users_status = models.BooleanField(default=True,verbose_name='статус пользователя')

    class Meta:

        permissions = [
        ('change_users_status', 'Can block/unblock user'),
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm , UserChangeForm
from users.models import User
from django import forms
class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email','password1','password2')

class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('email','phone','avatar')

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin , UserPassesTestMixin
from django.core.mail import send_mail
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy , reverse
from django.views.generic import CreateView , UpdateView , ListView, DetailView ,DeleteView

from services.services import send_newpassword
from users.models import User
from users.forms import UserRegisterForm , UserProfileForm
from django.conf import settings
import random

import secrets

class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        new_user = form.save()
        new_user.is_active = False
        token = secrets.token_hex(8)
        new_user.token = token
        new_user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/confirm/{token}'
        send_mail(
            subject="Подтверждение регистрации",
            message=f'Перейдите по ссылке для подтверждение регистрации {url}',
            from_email = settings.EMAIL_HOST_USER,
            recipient_list= [new_user.email]
        )
        return super().form_valid(form)

def email_verification(request,token):
    new_user = get_object_or_404(User,token=token)
    new_user.is_active = True
    new_user.save()
    return redirect(reverse_lazy('users:login'))

class UserUpdateView(LoginRequiredMixin,PermissionRequiredMixin,UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:user_list')
    login_url = 'users:login'
    permission_required = 'users.change_user'

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0,9)) for _ in range(8)])
    request.user.set_password(new_password)
    request.user.save()
    send_newpassword(request.user.email,new_password)
    return redirect(reverse('services:home'))



class UserListView(PermissionRequiredMixin,ListView):
    model = User
    permission_required = 'users.view_user'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args,**kwargs)
        context_data ['users_list'] = User.objects.all()
        return context_data

class UserDetailView(PermissionRequiredMixin,DetailView):
    model = User
    permission_required = 'users.view_user'


class UserDeleteView(UserPassesTestMixin,PermissionRequiredMixin,DeleteView):
    model = User
    permission_required = 'users.delete_user'
    login_url = 'users:login'
    success_url = reverse_lazy('users:user_list')

    def test_func(self):
        return self.request.user.is_staff

users/templates/users/login.html
{% extends 'services/base.html' %}

{% block content %}
    <div class="col-12">
            <form class='row' method="post" enctype="multipart/form-data">
                <div class="col-3"></div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Войти в профиль</h3>
                        </div>
                        <div class="card-body">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">Войти</button>
                        </div>
                    </div>
                </div>
            </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'services/base.html' %}

{% block content %}
    <div class="col-12">
            <form class='row' method="post" enctype="multipart/form-data">
                <div class="col-3"></div>
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Регистрация</h3>
                        </div>
                        <div class="card-body">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                        </div>
                    </div>
                </div>
            </form>
    </div>
{% endblock %}

users/templates/users/user_confirm_delete.html
{% extends 'services/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <form method="post" enctype="multipart/form-data">
                     <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Удалить пользователя</h3>
                                </div>
                            <div class="card-body">
                                    {% csrf_token %}
                                    <p>Действительно ли вы хотите удалить пользователя {{ user.email }} ?</p>
                                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                                    <a href="{% url 'services:client_list' %}" class="btn btn-warning">Отмена</a>
                            </div>
                        </div>
                     </div>
            </form>
        </div>
    </div>

{% endblock %}

users/templates/users/user_detail.html
{% extends 'services/base.html' %}
{% load static %}

<body>

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SkyService</h1>
    <p class="lead">Никнейм пользователя: {{ user.username | title }}</p>
</div>
  <div class="container">
    <div class="row">
         <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
              <span class="text-muted">Почта пользователя: {{ user.email }}</span><br>
              <span class="text-muted">Номер телефона : {{ user.phone }}</span>
            </div>
            <div class="card-footer">
            {% if perms.users.change_user or user.is_superuser %}
                <a type="button" href="{% url 'users:edit_user' user.pk%}" class="w-100 btn btn-lg btn-primary">Изменить</a>
            {% endif %}
            {% if perms.users.delete_user or user.is_superuser %}
                <a type="button" href="{% url 'users:delete_user' user.pk%}" class="w-100 btn btn-lg btn-primary">Удалить</a>
            {% endif %}
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock %}


</body>

users/templates/users/user_form.html
{% extends 'services/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <form method="post" enctype="multipart/form-data">
                     <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Профиль</h3>
                                </div>
                            <div class="card-body">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <button type="submit" class="btn btn-success">Сохранить</button>
                                    <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Восстановить пароль(Новый пароль будет отправлен на вашу почту)</a>
                            </div>
                        </div>
                     </div>
            </form>
        </div>
    </div>

{% endblock %}

users/templates/users/user_list.html
{% extends 'services/base.html' %}
{% load static %}


<body>

{% block content %}
    {% if perms.users.view_user or user.is_superuser %}
        {% for user in users_list %}
            <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
              <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                  <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Список пользователей</h4>
                  </div>
                  <div class="card-body">
                    <ul class="list-unstyled mt-3 mb-4">
                      <li>{{ user }}</li>
                    </ul>
                    <a type="button" href="{% url 'users:view_user' user.pk%}" class="w-100 btn btn-lg btn-primary">Информация</a>
                    {% if perms.users.change_user or user.is_superuser %}
                        <a type="button" href="{% url 'users:edit_user' user.pk%}" class="w-100 btn btn-lg btn-primary">Изменить</a>
                    {% endif %}
                    {% if perms.users.delete_user or user.is_superuser %}
                        <a type="button" href="{% url 'users:delete_user' user.pk%}" class="w-100 btn btn-lg btn-primary">Удалить</a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}


</body>