blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView,BlogCreateView, BlogUpdateView , BlogDetailView , BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('blogs_list',cache_page(60)(BlogListView.as_view()),name='blogs_list'),
    path('create_blog',BlogCreateView.as_view(),name='create_blog'),
    path('edit/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('view/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('delete/<int:pk>', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('services.urls',namespace='services')),
    path('users/',include('users.urls',namespace='users')),
    path('blog/',include('blog.urls',namespace='blog')),
]

services/urls.py
from django.urls import path
from services.apps import ServicesConfig
from services.views import Homepage,ContactTemplateView
from services.views import ClientCreateView,ClientListView,ClientDetailView,ClientUpdateView,ClientDeleteView
from services.views import MessageCreateView,MessageListView,MessageDetailView,MessageUpdateView,MessageDeleteView
from services.views import NewsletterCreateView,NewsletterUpdateView,NewsletterListView,NewsletterDetailView,NewsletterDeleteView
from services.views import LogsListView
from django.views.decorators.cache import cache_page

app_name = ServicesConfig.name


urlpatterns = [
    path('',cache_page(60)(Homepage.as_view()),name='home'),
    path('contacts/',ContactTemplateView.as_view(),name='contacts'),

    path('client_list/',ClientListView.as_view(),name='client_list'),
    path('create_client/',ClientCreateView.as_view(),name='create_client'),
    path('view_client/<int:pk>',ClientDetailView.as_view(),name='view_client'),
    path('edit_client/<int:pk>',ClientUpdateView.as_view(),name='edit_client'),
    path('delete_client/<int:pk>',ClientDeleteView.as_view(),name='delete_client'),

    path('message/create',MessageCreateView.as_view(),name='create_message'),
    path('message/list',MessageListView.as_view(),name='list_message'),
    path('message/view/<int:pk>',MessageDetailView.as_view(),name='view_message'),
    path('message/edit/<int:pk>',MessageUpdateView.as_view(),name='edit_message'),
    path('message/delete/<int:pk>',MessageDeleteView.as_view(),name='delete_message'),

    path('newsletter/create',NewsletterCreateView.as_view(),name='create_newsletter'),
    path('newsletter/edit/<int:pk>',NewsletterUpdateView.as_view(),name='edit_newsletter'),
    path('newsletter/list',NewsletterListView.as_view(),name='list_newsletter'),
    path('newsletter/view/<int:pk>',NewsletterDetailView.as_view(),name='view_newsletter'),
    path('newsletter/delete/<int:pk>',NewsletterDeleteView.as_view(),name='delete_newsletter'),

    path('logs/',LogsListView.as_view(),name='logs_list'),
]

services/models.py
from django.db import models
from django.conf import settings

NULLABLE = {'null': True, 'blank': True}

class Client(models.Model):
    email = models.EmailField(verbose_name='почта',unique=True)
    fio = models.CharField(max_length=70,verbose_name='ФИО')
    comment = models.TextField(verbose_name='комментарий',**NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,verbose_name='владелец',**NULLABLE)

    def __str__(self):
        return f'ФИО: {self.fio}, почта: {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    subject = models.CharField(max_length=30,verbose_name='тема письма')
    body = models.TextField(verbose_name='тело письма')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,verbose_name='владелец',**NULLABLE)

    def __str__(self):
        return f'{self.subject}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Newsletter(models.Model):
    start_time = models.DateTimeField(verbose_name='время начала отправки рассылки')
    end_time = models.DateTimeField(verbose_name='время окончания отправки рассылки')

    daily = 'раз в день'
    weekly = 'раз в неделю'
    monthly = 'раз в месяц'
    Periodicity = [
        (daily,'раз в день'),(weekly,'раз в неделю'),(monthly,'раз в месяц')
    ]
    periodicity = models.CharField(max_length=20,verbose_name='периодичность',choices=Periodicity)

    finished = 'завершена'
    created = 'создана'
    launched = 'запущена'
    Status = [
        (finished, 'завершена'), (created, 'создана'), (launched, 'запущена')
    ]
    status = models.CharField(max_length=20,verbose_name='статус рассылки',choices=Status,default=created)

    client = models.ManyToManyField(Client,verbose_name='клиент',**NULLABLE)
    message = models.ForeignKey(Message,verbose_name='сообщение',on_delete=models.CASCADE,**NULLABLE)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.SET_NULL,verbose_name='владелец',**NULLABLE)


    def __str__(self):
        return f'Время: {self.start_time} - {self.end_time}, статус рассылки: {self.status}, периодичность рассылки: {self.periodicity}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

        permissions = [
            ('change_status', 'Can change newsletters status'),
        ]


class Logs(models.Model):
    attempt = models.BooleanField(verbose_name='статус попытки')
    attempt_time = models.DateTimeField(verbose_name='дата и время последней попытки')
    response = models.CharField(max_length=100,verbose_name='ответ почтового сервера',**NULLABLE)

    newsletter = models.ForeignKey(Newsletter,verbose_name='рассылка',null=True,on_delete=models.SET_NULL)
    client = models.ForeignKey(Client,verbose_name='клиент',null=True,on_delete=models.SET_NULL)

    def __str__(self):
        return f'статус попытки: {self.attempt}, дата и время последней попытки: {self.attempt_time},ответ почтового сервера: {self.response}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'


class Contact(models.Model):
    name = models.CharField(max_length=50,verbose_name='Имя')
    number = models.TextField(verbose_name='Номер телефона')
    email = models.EmailField(verbose_name='Email')

    def __str__(self):
        return f'{self.name} {self.number}'

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакты"

services/forms.py
from django import forms
from services.models import Client,Message,Newsletter,Logs

class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('fio', 'email', 'comment',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('subject', 'body',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class NewsletterForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = ('start_time', 'end_time','periodicity','status','client','message')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

services/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView,UpdateView,ListView,DetailView,DeleteView,TemplateView

from blog.models import Blog
from services.models import Client, Message, Newsletter, Contact, Logs
from services.forms import ClientForm, MessageForm, NewsletterForm
from services.services import homepage_cache


class Homepage(TemplateView):
    template_name = 'services/base.html'
    # random_article = Blog.objects.order_by('?')[:3]
    extra_context = {'title':'SkyService','filtred_list': homepage_cache()}

class ClientCreateView(LoginRequiredMixin,CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('services:client_list')
    login_url = 'users:login'

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)

class ClientUpdateView(LoginRequiredMixin,UpdateView):
    model = Client
    fields = ('fio', 'email', 'comment',)
    success_url = reverse_lazy('services:client_list')
    login_url = 'users:login'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner == self.request.user or self.request.user.is_superuser:
            return self.object
        else:
            raise Http404

class ClientListView(LoginRequiredMixin,ListView):
    model = Client
    success_url = reverse_lazy('services:client_list')
    login_url = 'users:login'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(id=self.kwargs.get('pk'))
        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args,**kwargs)
        context_data ['clients_list'] = Client.objects.all()
        return context_data

class ClientDetailView(LoginRequiredMixin,DetailView):
    model = Client
    login_url = 'users:login'

class ClientDeleteView(LoginRequiredMixin,DeleteView):
    model = Client
    success_url = reverse_lazy('services:client_list')
    login_url = 'users:login'

class MessageCreateView(LoginRequiredMixin,CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('services:list_message')
    login_url = 'users:login'

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)

class MessageUpdateView(LoginRequiredMixin,UpdateView):
    model = Message
    fields = ('subject', 'body',)
    success_url = reverse_lazy('services:list_message')
    login_url = 'users:login'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user:
            raise Http404
        return self.object
class MessageListView(LoginRequiredMixin,ListView):
    model = Message
    success_url = reverse_lazy('services:list_message')
    login_url = 'users:login'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['message_list'] = Message.objects.all()
        return context_data

class MessageDetailView(DetailView):
    model = Message


class MessageDeleteView(LoginRequiredMixin,DeleteView):
    model = Message
    success_url = reverse_lazy('services:list_message')
    login_url = 'users:login'


class NewsletterCreateView(LoginRequiredMixin,CreateView):
    model = Newsletter
    form_class = NewsletterForm
    success_url = reverse_lazy('services:list_newsletter')
    login_url = 'users:login'

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)

class NewsletterUpdateView(LoginRequiredMixin,UpdateView):
    model = Newsletter
    fields = ('start_time', 'end_time', 'periodicity', 'status', 'client', 'message')
    success_url = reverse_lazy('services:list_newsletter')
    login_url = 'users:login'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner == self.request.user or self.request.user.is_superuser:
            return self.object
        else:
            raise Http404


class NewsletterListView(LoginRequiredMixin,ListView):
    model = Newsletter
    success_url = reverse_lazy('services:list_newsletter')
    login_url = 'users:login'
    # permission_required = 'services.view_newsletter'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['newsletter_list'] = Newsletter.objects.all()
        unique_clients = Client.objects.all().count()
        context_data['clients'] = unique_clients
        return context_data

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(id=self.kwargs.get('pk'))
        if not self.request.user.is_staff:
            queryset = queryset.filter(owner = self.request.user)
        return queryset
class NewsletterDetailView(DetailView):
    model = Newsletter

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(id=self.kwargs.get('pk'))
        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)
        return queryset

class NewsletterDeleteView(LoginRequiredMixin,DeleteView):
    model = Newsletter
    success_url = reverse_lazy('services:list_newsletter')
    login_url = 'users:login'


class ContactTemplateView(TemplateView):
    template_name = 'services/contacts.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        contact_info = Contact.objects.all()
        context_data['contact_book'] = contact_info
        return context_data

    def post(self,request):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Имя:{name} , номер телефона:{phone} , сообщение: {message}')
        return render(request,self.template_name)


class LogsListView(LoginRequiredMixin,ListView):
    model = Logs
    success_url = reverse_lazy('services:logs_list')
    login_url = 'users:login'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['total'] = Logs.objects.all()
        context_data['total_count'] = Logs.objects.all().count()
        context_data['successful_count'] = Logs.objects.filter(attempt=True).count()
        context_data['unsuccessful_count'] = Logs.objects.filter(attempt=False).count()
        return context_data

services/templates/services/client_confirm_delete.html
{% extends 'services/base.html' %}
{% load static %}

<!DOCTYPE html>
{% block icon %}
    <title>Удалить клиента</title>
{% endblock %}


{% block content %}
    {% if user.is_superuser or client.owner == request.user or perms.services.delete_client%}
        <div class="col-12">
                <form class='row' method="post" enctype="multipart/form-data">
                    <div class="col-6">
                        <div class="card">
                            <div class="card-body">
                                <div class="card-header">
                                    <h3 class="card-title">Удалить клиента</h3>
                                </div>
                                    {% csrf_token %}
                                     <p>Действительно ли вы хотите удалить клиента {{ client.fio }} ?</p>
                                    <button type="submit" class="btn btn-danger">Подтвердить</button>
                                    <a href="{% url 'services:client_list' %}" class="btn btn-warning">Отмена</a>
                            </div>
                        </div>
                    </div>
                </form>
        </div>
    {% else %}
        У вас нету прав для удаления клиента "{{ client.fio }}"
    {% endif %}
{% endblock %}

services/templates/services/client_detail.html
{% extends 'services/base.html' %}
{% load static %}

<!DOCTYPE html>
{% block icon %}
    <title>Добавить клиента</title>
{% endblock %}

</head>
<body>

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SkyService</h1>
    <p class="lead">Ф.И.О клиента: {{ client.fio | title }}</p>
</div>
  <div class="container">
    <div class="row">
         <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
              <span class="text-muted">Почта клиента: {{ client.email }}</span><br>
              <span class="text-muted">Комментарий: {{ client.comment }}</span>
            </div>
            <div class="card-footer">
              <a class="btn btn-link" href="{% url 'services:edit_client' client.pk%}">Изменить</a>
              <a class="btn btn-link" href="{% url 'services:delete_client' client.pk%}">Удалить</a>
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock %}


</body>
</html>

services/templates/services/client_form.html
{% extends 'services/base.html' %}
{% load static %}

<!DOCTYPE html>
{% block icon %}
    <title>Добавить клиента</title>
{% endblock %}


{% block content %}
    <div class="col-12">
            <form class='row' method="post" enctype="multipart/form-data">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <div class="card-header">
                                <h3 class="card-title">Создать клиента</h3>
                            </div>
                                {% csrf_token %}
                                {{ form.as_p }}
                                 {% if client %}
                                    <br><button type="submit" class="btn btn-success">Сохранить</button>
                                 {% else %}
                                    <br><button type="submit" class="btn btn-success">Создать</button>
                                 {% endif %}
                        </div>
                    </div>
                </div>
            </form>
    </div>
{% endblock %}

services/templates/services/client_list.html
{% extends 'services/base.html' %}
{% load static %}

<!DOCTYPE html>
{% block icon %}
    <title>Список клиентов</title>
{% endblock %}

</head>
<body>

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">SkyService</h1>
        <p class="lead">Добро пожаловать ^_^</p>
    </div>

  <main>
    {% for client in clients_list %}
      {% if user.is_superuser or client.owner == request.user or perms.services.view_client%}
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Ф.И.О клиента: {{ client.fio | title }}</h4>
              </div>
              <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                  <li>Почта клиента: {{ client.email }}</li>
                </ul>
                <a type="button" href="{% url 'services:view_client' client.pk%}" class="w-100 btn btn-lg btn-primary">Информация</a>
                <a type="button" href="{% url 'services:edit_client' client.pk%}" class="w-100 btn btn-lg btn-primary">Изменить</a>
                <a type="button" href="{% url 'services:delete_client' client.pk%}" class="w-100 btn btn-lg btn-primary">Удалить</a>
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </main>
   <div class="col-12 mb-5">
      <a href="{% url 'services:create_client' %}" class="btn btn-outline-primary">Добавить клиента</a>
   </div>
{% endblock %}


</body>
</html>

services/templates/services/contacts.html
{% extends 'services/base.html' %}
{% load static %}
<!doctype html>
{% block icon %}
    <title>Контакты</title>
    <link rel="icon" href="{% static 'images/contacts.png' %}" type="image/x-icon">
{% endblock %}


{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    {%  for contact in contact_book %}
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Турция</td>
                        </tr>
                        <tr>
                            <td class="w-25">Номер для связи</td>
                            <td>{{ contact.number }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Наш e-mail</td>
                            <td>{{ contact.email }}</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Кадыкей,Стамбул</td>
                        </tr>
                    </table>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Ваш отзыв" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

</body>
</html>

services/templates/services/message_detail.html
{% extends 'services/base.html' %}
{% load static %}

<!DOCTYPE html>
{% block icon %}
    <title>Информация о сообщении</title>
{% endblock %}

</head>
<body>

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SkyService</h1>
    <p class="lead">Тема письма: {{ message.subject| title }} </p>
</div>
  <div class="container">
    <div class="row">
         <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
              <span class="text-muted">Тело письма: {{ message.body }}</span><br>
            </div>
            <div class="card-footer">
              {% if perms.services.change_message or user.is_superuser or message.owner == request.user %}
                <a class="btn btn-link" href="{% url 'services:edit_message' message.pk%}">Изменить</a>
              {% endif %}
              {% if user.is_superuser or newsletter.owner == request.user or message.owner == request.user %}
                <a class="btn btn-link" href="{% url 'services:delete_message' message.pk%}">Удалить</a>
              {% endif %}
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock %}


</body>
</html>

services/templates/services/message_list.html
{% extends 'services/base.html' %}
{% load static %}

<!DOCTYPE html>
{% block icon %}
    <title>Список писем</title>
{% endblock %}

</head>
<body>

{% block content %}
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">SkyService</h1>
        <p class="lead">Добро пожаловать ^_^</p>
    </div>

  <main>
    {% for message in message_list %}
      {% if user.is_superuser or message.owner == request.user %}
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
          <div class="col">
            <div class="card mb-4 rounded-3 shadow-sm">
              <div class="card-header py-3">
                <h4 class="my-0 fw-normal">Тема письма: {{ message.subject }}</h4>
              </div>
              <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                  <li>Тело письма: {{ message.body }}</li>
                </ul>
                <a type="button" href="{% url 'services:view_message' message.pk%}" class="w-100 btn btn-lg btn-primary">Информация</a>
                {% if perms.services.change_message or user.is_superuser or message.owner == request.user %}
                    <a type="button" href="{% url 'services:edit_message' message.pk%}" class="w-100 btn btn-lg btn-primary">Изменить</a>
                {% endif %}
                {% if user.is_superuser or newsletter.owner == request.user or message.owner == request.user %}
                    <a type="button" href="{% url 'services:delete_message' message.pk%}" class="w-100 btn btn-lg btn-primary">Удалить</a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      {% endif %}
    {% endfor %}
  </main>
   <div class="col-12 mb-5">
      <a href="{% url 'services:create_message' %}" class="btn btn-outline-primary">Добавить Сообщение</a>
   </div>
{% endblock %}


</body>
</html>

services/templates/services/newsletter_detail.html
 {% extends 'services/base.html' %}
{% load static %}

<!DOCTYPE html>
{% block icon %}
    <title>Информация о рассылки</title>
{% endblock %}

</head>
<body>

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">SkyService</h1>
</div>
  <div class="container">
    <div class="row">
         <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <div class="card-body">
                {% for item in newsletter.client.all %}
                   <span class="text-muted">Ф.И.О клиента: {{ item.fio }}</span><br>
                   <span class="text-muted">Почта клиента: {{ item.email }}</span><br>
                {% endfor %}
                {% for i in newsletter.message.all %}
                    <h4 class="my-0 fw-normal">Тема письма: {{ i.subject }} </h4>
                {% endfor %}
            </div>
            <div class="card-footer">
              {% if newsletter.owner == request.user or user.is_superuser or perms.services.change_newsletter%}
                <a class="btn btn-link" href="{% url 'services:edit_newsletter' newsletter.pk%}">Изменить</a>
              {% endif %}
              {% if user.is_superuser or newsletter.owner == request.user or perms.services.delete_newsletter%}
                <a class="btn btn-link" href="{% url 'services:delete_newsletter' newsletter.pk%}">Удалить</a>
              {% endif %}
            </div>
          </div>
        </div>
    </div>
  </div>
{% endblock %}


</body>
</html>